services:
  backend:
    image: $DOCKER_REGISTRY
    container_name: modhelper_backend
    ports:
      - "8000:8000"
    volumes:
      - ./data/sqlite3:/app/sqlite3
      - ./data/chromadb:/app/chromadb
    depends_on:
      - neo4j
      - mongodb
    env_file:
      - .env
    environment:
      - NEO4J_URL=bolt://neo4j:7687
      - MONGO_URL=mongodb://mongodb:27017
      - ALLOW_ORIGINS='["http://modhelper_frontend:80", "ws://modhelper_frontend:8000"]'
      - LLM_API_KEY=$LLM_API_KEY
      - EMBEDDING_API_KEY=$EMBEDDING_API_KEY
      - NEO4J_PASSWORD=$NEO4J_PASSWORD
    networks:
      - modhelper_net

  neo4j:
    image: neo4j:5
    container_name: neo4j
    ports:
      - "7474:7474"     # 浏览器访问 Neo4j Studio
      - "7687:7687"     # Bolt 协议，代码连接
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - ./data/neo4j/data:/data
      - ./data/neo4j/logs:/logs
      - ./data/neo4j/import:/var/lib/neo4j/import
      - ./data/neo4j/plugins:/plugins
    networks:
      - modhelper_net
  
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb/data:/data/db
    networks:
      - modhelper_net

networks:
  modhelper_net:
    name: modhelper_net